### ISSUE TITLE
[NavMesh Generator Website] Generate NavMesh in web worker

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#130]

**Comment by GGAlanSmithee** [comment]
Hey! Since this issue is more specifically about using workers on the site, does that imply that the package is usable from a web worker, or is this issue about adding support for that?

**Comment by isaac-mason** [comment]
Hey @GGAlanSmithee! That's right - this library already provides primitives to help you do nav mesh generation in a web worker.

I've created a separate issue to track adding docs and an example for this: https://github.com/isaac-mason/recast-navigation-js/issues/225

I've also put a high-level description of what you'd need to do on that issue.

**Comment by GGAlanSmithee** [comment]
hey @isaac-mason just to let you know, the outline described in #225 works fine! However, in my case, the overhead of passing the data back and forth to the worker (using three.js meshes) makes it a bad drop-in replacement. With that said, I could probably refactor my code to build the scene within the worker. I will try that next.

**Comment by isaac-mason** [comment]
@GGAlanSmithee good to hear you've got something working at least!

Out of curiosity, how are you sending the meshes to the worker for nav mesh generation? Are using transferables? E.g. using [`getPositionsAndIndcies` from `recast-navigation/three`](https://github.com/isaac-mason/recast-navigation-js/blob/main/packages/recast-navigation-three/src/utils/get-positions-and-indices.ts) (or something like it) and sending the positions and indices as transferables?

**Comment by GGAlanSmithee** [comment]
> If not, that could potentially be the source of your overhead.

Yeah, I was just naively sending the meshes as is, which I knew would result in this overhead, but just wanted to see if it worked  at all (which it did).

I did not know about transferables, thanks a lot for the links, I will read up on it.

**Comment by GGAlanSmithee** [comment]
I've done some testing and using the method you describe (getting points and indexes, sending them to a worker as buffers, constructing the navmesh, exporting it, sending it back, and re-constructing it) and it is still taking quite some time.

The map I am using is sectioned into discrete chunks, so I could easily split it up, build the navmeshes in parallell and stitch it together.

if you want to check it out, a deb build is available here: https://playground.edenever.online/

1. draw on the map
2. hit "d" to play (and generate navmesh) (open console first to see timers)

![image](https://github.com/isaac-mason/recast-navigation-js/assets/11805103/d99e2a36-0aa8-4df3-8318-9050bf0dd97f)

**Comment by GGAlanSmithee** [comment]
I can def. simplify this majorly logically, so I will do some sweeping changes before testing more

**Comment by isaac-mason** [comment]
Interesting, thanks for sharing the link @GGAlanSmithee 🙂 

If you haven't already, you can try tweaking `cs` (cell size) and `ch` (cell height) if you don't need as much precision to try to speed up nav mesh generation as well.

**Comment by GGAlanSmithee** [comment]
> If you haven't already, you can try tweaking cs (cell size) and ch (cell height) if you don't need as much precision to try to speed up nav mesh generation as well.

Yes, I am currently doing this (with great results so far) as well as simplifying / excluding meshes, I am getting reasonable times now, since this will be done ahead of time outside of the design tool.

Thanks for your continued help!

**Comment by GGAlanSmithee** [comment]
simplified meshes used for navmesh and tweaked ch+cs

![image](https://github.com/isaac-mason/recast-navigation-js/assets/11805103/3e490861-76e9-484e-ac57-3b045ac494f2)

**Comment by isaac-mason** [comment]
That's an awesome improvement! And no worries at all @GGAlanSmithee, happy to help 😄

**Comment by isaac-mason** [comment]
Closing this for now as not planned.
