### ISSUE TITLE
Improve three debug helpers

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#165]
NavMeshHelper needs several improvements, it's not as useful as the visualisations in RecastDemo.

**Comment by isaac-mason** [comment]
Consider just implementing `duDebugDraw` and using recastnavigation's debugging utilities: https://github.com/recastnavigation/recastnavigation/blob/main/DebugUtils/Include/DebugDraw.h#L34

**Comment by isaac-mason** [comment]
Some progress implementing duDebugDraw:

<img width="687" alt="image" src="https://github.com/isaac-mason/recast-navigation-js/assets/67411435/5a17926c-7778-4976-9160-7db3a942d22b">

**Comment by isaac-mason** [comment]
https://github.com/isaac-mason/recast-navigation-js/tree/feat/duDebugDraw

**Comment by isaac-mason** [comment]
`duDebugDrawRawContours`

<img width="1000" alt="image" src="https://github.com/isaac-mason/recast-navigation-js/assets/67411435/c62a0777-bfae-4861-9980-1aeb5f3cf4d8">

**Comment by isaac-mason** [comment]
https://recast-navigation-js.isaacmason.com/?path=/story/debug-three-debug-drawer--poly-mesh

**Comment by isaac-mason** [comment]
0.25.0 of recast-navigation/three has a new DebugDrawer class

Still a WIP - some TileCache methods need to be exposed to support visualising TIleCache intermediates.

**Comment by GGAlanSmithee** [comment]
> `duDebugDrawRawContours`
> 
> <img alt="image" width="1000" src="https://private-user-images.githubusercontent.com/67411435/325027646-c62a0777-bfae-4861-9980-1aeb5f3cf4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjIzNDQsIm5iZiI6MTcxNDA2MjA0NCwicGF0aCI6Ii82NzQxMTQzNS8zMjUwMjc2NDYtYzYyYTA3NzctYmZhZS00ODYxLTk5ODAtMWFlYjVmM2NmNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE2MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYjU0MmZiZDkzMzRhODQ4MDJjNzJhOTVkYzQwMjFjNTQ2YTUyZjFhYjk2MGEyN2UwNGM5ODFkYjc2NDM1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F0qEOuewoeMGuzdw-9rCJgCce3RExkMUJXe0AY8VKUw">

this is amazing!

**Comment by isaac-mason** [comment]
The debug helpers can still use more improvement, and TileCache helpers should get exposed but the helpers released in v0.25.0 were a huge leap forward.

Closing this issue and opening a new one for TileCache helpers.
