### ISSUE TITLE
Add docs and example demonstrating how to generate a NavMesh in a worker 

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#225]
This library already provides primitives that help with generating a nav mesh in a worker, but the worker orchestration needs to be done in user-land.

High-level steps:
- Inside a web worker, use the library to create a navmesh (e.g. with a high-level generator such as `generateSoloNavMesh`)
- Export the navmesh with `exportNavMesh` to get a transferable `uInt8Array`
- Post the `uInt8Array` nav mesh export to the main thread
- Use `importNavMesh` on the main thread, passing in the `uInt8Array` export

**Comment by Samsy** [comment]
<img width="642" alt="Screenshot 2024-03-01 at 15 00 33" src="https://github.com/isaac-mason/recast-navigation-js/assets/3786958/142989e5-543d-4d57-87de-b92b9d344977">


Trying to import and generate inside a webworker, but got no chances yet 


`import { init, exportNavMesh } from 'recast-navigation';

import { generateTiledNavMesh  } from 'recast-navigation/generators';


var controller, signal, url;
var isInit;

self.addEventListener(
    "message",

    async function (e) {

        if (e.data.abort == true && controller != null) {
            controller.abort();

            return;
        }

        if(e.data.type == 'generate') {

            if( isInit == false ) {
                
                await init()

                console.log('init navmesh worker')

                isInit = true
            }
    
            const positions = e.data.positions;
    
            const parameters = e.data.parameters;
    
            const indices = e.data.indices

            var generated = generateTiledNavMesh(
                positions,
                indices,
                parameters
            )

            console.log( generated )

            // var binary = exportNavMesh( generated )

            // console.log('generated navmesh')
            // console.log(binary)

            // self.postMessage({
            //     jobID : e.data.jobID,
            //     binary: binary
            // });
        }
    },
    false
);
`

**Comment by isaac-mason** [comment]
https://github.com/isaac-mason/recast-navigation-js/commit/c3e89bd10f5782bf046a61737f6dc09d981d4b33
