### ISSUE TITLE
Cannot read properties of undefined (reading 'RecastBuildContextImpl')

### ISSUE THREAD

**Issue by GGAlanSmithee** [isaac-mason/recast-navigation-js#284]
With latest versions of `three` and `@react-three/fiber` and `@react-three/drei`, I am getting this error: `Cannot read properties of undefined (reading 'RecastBuildContextImpl')` (see the screenshot below)

I interpret this as the WASM module not loading correctly, but could be mistaken. Not exactly sure at what point this broke. I was able to get it working by downgrading three and/or react-three at one point, but not sure what the offending version(s) are.

![image](https://github.com/isaac-mason/recast-navigation-js/assets/11805103/3105cd12-3e6f-435f-9e7d-3767288e9761)

**Comment by isaac-mason** [comment]
Hi @GGAlanSmithee, the most common reason for this is `init` hasn't been called / it's promise hasn't been resolved before using the library.

If you can share more code / a codesandbox I'll take a look 🙂

**Comment by GGAlanSmithee** [comment]
Thanks @isaac-mason I will try to create a minimal reproduction. Interestingly though, this has been working for months, and I haven't changed anything else that I know of, other than increasing the versions of said packages.

I will see if I can isolate it.

**Comment by GGAlanSmithee** [comment]
turns out there is an issue with how the `<Text />` component from `@react-three/drei` uses `suspend` ever since version `9.99.3` of that package, or this commit: https://github.com/pmndrs/drei/pull/1841/files

* here is an issue in their repo: https://github.com/pmndrs/drei/issues/1886
* here is a reproduction: https://github.com/GGAlanSmithee/react-three-dre-text-bug-reproduction

I will close this issue because the problem is (almost certainly) not related to this package

**Comment by FrameMuse** [comment]
@isaac-mason, I think it's worth to add an error if the recast-navigation wasn't inited. I had the same issue and I struggled for 1 hour. I googled several times, but it didn't lead me to this page.

**Comment by isaac-mason** [comment]
Hey @FrameMuse, I should at the very least make this more promiment in the readme.

I'd want to check that the overhead of doing a check for whether recast is initialised on every operation won't degrade performance.

Maybe a middle ground could be checking if init has been called in a few key places, e.g. in the high level generators like `generateSoloNavMesh` / `threeToSoloNavMesh`, which most folks start with anyway.
