### ISSUE TITLE
Fix generateTileCache / threeToTileCache typescript types to omit unsupported RecastConfig options

### ISSUE THREAD

**Issue by Aaron-Bird** [isaac-mason/recast-navigation-js#313]
You can preview the demo from the URL：https://aaron-bird.github.io/recast-navigation-js-issue-demo/index.html
Or download it：https://github.com/Aaron-Bird/recast-navigation-js-issue-demo

Some code：

```js
 const { success, navMesh, tileCache } = threeToTileCache([mesh], {
            tileSize: 16,
            cs: 0.2,
            ch: 0.2,
            walkableSlopeAngle: 35,
            walkableHeight: 1,
            walkableClimb: 0.1,
            walkableRadius: 1,
            maxEdgeLen: 12,
            maxSimplificationError: 1.3,
            mergeRegionArea: 20,
            maxVertsPerPoly: 6,
            detailSampleDist: 6,
            detailSampleMaxError: 1,

            minRegionArea: 100,
          });
```

**Comment by isaac-mason** [comment]
Hi, I beleive this is a simialr issue to this: https://github.com/isaac-mason/recast-navigation-js/discussions/308

**Comment by isaac-mason** [comment]
The short explanation is the Detour TileCache generation process is different to the process for solo and tiled navigation meshes, and it appears although TileCache takes a `rcConfig` / recast configuration object with a minRegionArea option, it isn't actually used.

I think we should at least fix the typescript types so it doesn't seem like minRegionArea + maxEdgeLen + potentially others can be used, when in reality they cant.

**Comment by isaac-mason** [comment]
Made a change to omit `minRegionArea` and `maxEdgeLen` from `TileCacheGeneratorConfig`
https://github.com/isaac-mason/recast-navigation-js/commit/5cb17a14b0399c57872c2fb6537783c2d202f0f4
