### ISSUE TITLE
Expose decodePolyId and encodePolyId

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#314]
Related discussion: https://github.com/isaac-mason/recast-navigation-js/discussions/307

**Comment by rob-myers** [comment]
I intend to implement this, following the pattern of [my previous PR](https://github.com/isaac-mason/recast-navigation-js/pull/300).

**Comment by rob-myers** [comment]
I've [submitted a PR](https://github.com/isaac-mason/recast-navigation-js/pull/325).

**Comment by isaac-mason** [comment]
Thanks @rob-myers! Released in v0.21.0 🙂
