### ISSUE TITLE
Exporting with tileCache seems to be working but causes an error when importing

### ISSUE THREAD

**Issue by DVLP** [isaac-mason/recast-navigation-js#319]
When exporting like this `exportNavMesh(navMesh)` it works and the result can be correctly imported.

When exporting like this `exportNavMesh(navMesh, tileCache)` then it seems to be working but when trying to import the buffer it throws an error in wasm about an unknown function

**Comment by DVLP** [comment]
![image](https://github.com/isaac-mason/recast-navigation-js/assets/5261364/82dd3738-6e49-4642-b809-be00d6faf8c8)

**Comment by isaac-mason** [comment]
Hi @DVLP, thanks for reporting this.

There is a storybook example for importing and exporting a navmesh and a tilecache you can check your usage against: https://recast-navigation-js.isaacmason.com/?path=/story/utilities-importing-and-exporting--tile-cache-example

If you can provide your code / a minimal reproduction, I'll take a look 🙂

**Comment by DVLP** [comment]
My bad, importNavMesh requires a second parameter when exporting with tileCache.
