### ISSUE TITLE
Allow setting the maxStraightPathPolys parameter in computePath

### ISSUE THREAD

**Issue by Aaron-Bird** [isaac-mason/recast-navigation-js#327]
The maxStraightPathPolys parameter in computePath cannot be set
Pathfinding results may exceed 256 in some complex paths
https://github.com/isaac-mason/recast-navigation-js/blob/3284f31c3d54b091f6af589672d22afb15acea70/packages/recast-navigation-core/src/nav-mesh-query.ts#L338

Like this demo, you can click on different locations to get the path： 
https://aaron-bird.github.io/recast-navigation-js-issue-demo/index-3.html

Or download it： 
https://github.com/Aaron-Bird/recast-navigation-js-issue-demo

**Comment by isaac-mason** [comment]
Hi @Aaron-Bird, thanks for the issue. 

This has been added in: https://github.com/isaac-mason/recast-navigation-js/commit/cb6290c4c5df24cff358f62a83c08ddf9573505e

It will be released shortly.

Let me know if you run into issues with it.

**Comment by Aaron-Bird** [comment]
So fast.You are my superhero.

**Comment by Aaron-Bird** [comment]
Updated to version 0.24, the returned results are incorrect when the path is very long.
There is no difference in path results with maxPathPolys 500 and 1000.
think maybe there is some parameter limit in recastnavigation.

https://aaron-bird.github.io/recast-navigation-js-issue-demo/index-4.html
