### ISSUE TITLE
Give some control over NavMeshQuery random implementation 

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#332]
It may be useful to at least support initialising the random implementation with a seed.

**Comment by GGAlanSmithee** [comment]
this would be amazing in terms of being able to do deterministic randomness, which is needed for games that needs to be able to run simulations on different clients, with an expected outcome, given the same input, such as RTS:s.

**Comment by isaac-mason** [comment]
https://github.com/isaac-mason/recast-navigation-js/commit/225a983092b2f1623c37e1659659377ebaad9aae
