### ISSUE TITLE
use requestMoveTarget but the agent don't move

### ISSUE THREAD

**Issue by fangliangv587** [isaac-mason/recast-navigation-js#414]
the version is  0.33.0，i use vite + vue3 + threejs version166，when i use the requestMoveTarget  api ，and return true，find the agent rotate but not move ，i dont know why。otherwise，when i use  the teleport api，the agent can move dst point，why the requestMoveTarget   doesn't work？

**Comment by isaac-mason** [comment]
Hi @fangliangv587,

I don't have much to go off here to help you. If you can provide a codesandbox or repo demonstrating your issue I'm happy to take a look 🙂

**Comment by fangliangv587** [comment]
> Hi @fangliangv587,
> 
> I don't have much to go off here to help you. If you can provide a codesandbox or repo demonstrating your issue I'm happy to take a look 🙂

i change the office demo 【navmesh-website】to vue，the main code in App.vue ,run the code you will find the performance above。thank you very much。
the code is in
 [nav-test-master.zip](https://github.com/user-attachments/files/16318820/nav-test-master.zip) or [https://gitee.com/fangliangv587/nav-test]

**Comment by fangliangv587** [comment]
i solve it.the code 'crowd.update(delta);' delta is undefine. i am sorry. thank you any more .

**Comment by isaac-mason** [comment]
Sorry I didn't get a chance to look at this, but glad to hear you solved your issue @fangliangv587! 🙂

**Comment by isaac-mason** [comment]
It sounds like `undefined` was being treated as zero, so detour would determine the desired movement direction, but then multiply it by 0. That would explain why agnets rotated but didn't move.
