### ISSUE TITLE
Disable certain offMeshConnection

### ISSUE THREAD

**Issue by LukeStonehm** [isaac-mason/recast-navigation-js#437]
Good day,

I was wondering if it's at all possible to disable certain offMeshConnections. In our use case, we're making a building map, which has multiple levels. If the user selected "wheelchair", we don't want recast to path via the stairs.

Is that possible to achieve? I tried playing around with the connections' flags, and the navMeshQuery's "exclude" & "include" filters, but couldn't achieve anything meaningful. 

My next plan, which is kinda hacky / brute force, is to generate two navMeshes, once for accessibility & non-accessibility.

Thanks for your time :smile:

**Comment by isaac-mason** [comment]
Hey @LukeStonehm!

Having two navmeshes with different walkableClimb and walkableSlopeAngle values would be a common approach for things like this with recast. It's also common to create multiple navmeshes for e.g. agents of different sizes. 

There isn't an example in the repo for this yet, but you should be able to assign flags to off mesh connections, and create nav mesh query filters that include or exclude flags from being considered in the query.

There is a related example for custom areas and query filters here:

https://recast-navigation-js.isaacmason.com/?path=/story/advanced-custom-areas--compute-path
https://github.com/isaac-mason/recast-navigation-js/blob/main/packages/recast-navigation/.storybook/stories/advanced/custom-areas.stories.tsx

**Comment by LukeStonehm** [comment]
Thanks @isaac-mason I'll review that example and see what I can do. I'll close this. Thanks very much for the assistance.
