### ISSUE TITLE
Add support for custom bounds bbMin & bbMax

### ISSUE THREAD

**Issue by yelouafi** [isaac-mason/recast-navigation-js#451]
Sometimes it's not desirable to include a whole mesh but only part of it, for example I have a huge terrain but I don't need the agent to navigate the whole area. Initially I thought I'll just restrict the vertices passed to generate function but it doesn't work as expected because the triangles that partially intersect the bbox will be excluded. I noticed recast takes `bbMin` & `bbMax` in the config but those are auto computed from the passed vertices in recast-js. And there's no option to restrict further the computed bounds.

It's my understanding that bbMin & bbMax affects the generated heightfield and so will result in faster gen time and allow more precise values for cs. Does it make sense to add support for those in the lib. I did some tests on a custom impl. of generateSoloNavMesh and seems to work as expected. I just passed the custum bounds to [getBoundingBox](https://github.com/isaac-mason/recast-navigation-js/blob/b5679037b877003ec2c59332d23df4d5f4e53a7e/packages/recast-navigation-generators/src/generators/common.ts#L3) and adjusted the returned bbMin & bbMax.

I can PR If there's no issue

**Comment by isaac-mason** [comment]
I'd be very happy with adding optional bounds arguments to the included generators that skip calling getBoundingBox if present, sounds very reasonable to me.

I can find some time for this sometime, otherwise I'd happily accept a PR for this too.

**Comment by isaac-mason** [comment]
I've added an optional 'bounds' argument to the included generators now: https://github.com/isaac-mason/recast-navigation-js/commit/93d383ebb9e8373ab982b0de005d395d09a99eb6
